/*
 *    Copyright 2019 West Coast Informatics, LLC
 */
package com.wci.umls.server.jpa.algo.invert;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.UUID;

import com.wci.umls.server.AlgorithmParameter;
import com.wci.umls.server.ValidationResult;
import com.wci.umls.server.helpers.ConfigUtility;
import com.wci.umls.server.helpers.FieldedStringTokenizer;
import com.wci.umls.server.helpers.LocalException;
import com.wci.umls.server.jpa.AlgorithmParameterJpa;
import com.wci.umls.server.jpa.ValidationResultJpa;
import com.wci.umls.server.jpa.algo.AbstractInsertMaintReleaseAlgorithm;

/**
 * Implementation of an algorithm to save information before an insertion.
 */
public class ValidateAtomsAlgorithm extends AbstractInsertMaintReleaseAlgorithm {

  private String srcFullPath;
  
  /** The check names. */
  private List<String> checkNames;
  
  /**
   * Instantiates an empty {@link ValidateAtomsAlgorithm}.
   * @throws Exception if anything goes wrong
   */
  public ValidateAtomsAlgorithm() throws Exception {
    super();
    setActivityId(UUID.randomUUID().toString());
    setWorkId("VALIDATEATOMS");
    setLastModifiedBy("admin");
  }

  /**
   * Check preconditions.
   *
   * @return the validation result
   * @throws Exception the exception
   */
  /* see superclass */
  @Override
  public ValidationResult checkPreconditions() throws Exception {

    ValidationResult validationResult = new ValidationResultJpa();

    if (getProject() == null) {
      throw new LocalException("Atom Validation requires a project to be set");
    }

    // Go through all the files needed by insertion and check for presence
    // Check the input directories
    srcFullPath =
        ConfigUtility.getConfigProperties().getProperty("source.data.dir") + "/"
            + getProcess().getInputPath();

    final Path realPath = Paths.get(srcFullPath).toRealPath();
    setSrcDirFile(new File(realPath.toString()));

    if (!getSrcDirFile().exists()) {
      throw new LocalException(
          "Specified input directory does not exist - " + srcFullPath);
    }

    checkFileExist(srcFullPath, "classes_atoms.src");
    checkFileExist(srcFullPath, "sources.src");
    checkFileExist(srcFullPath, "termgroups.src");

    // Ensure permissions are sufficient to write files
    try {
      final File outputFile = new File(srcFullPath, "testFile.txt");

      final PrintWriter out = new PrintWriter(new FileWriter(outputFile));
      out.print("Test");
      out.close();

      // Remove test file
      outputFile.delete();
    } catch (Exception e) {
      throw new LocalException("Unable to write files to " + srcFullPath
          + " - update permissions before continuing validation.");
    }

    // Makes sure editing is turned off before continuing
    /*if(getProject().isEditingEnabled()){
      throw new LocalException("Editing is turned on - disable before continuing insertion.");
    }*/
    
    // Makes sure automations are turned off before continuing
    if(getProject().isAutomationsEnabled()){
      throw new LocalException("Automations are turned on - disable before continuing validation.");
    }
    
    return validationResult;
  }

  /**
   * Check file exist.
   *
   * @param srcFullPath the src full path
   * @param fileName the file name
   * @throws Exception the exception
   */
  @SuppressWarnings("static-method")
  private void checkFileExist(String srcFullPath, String fileName)
    throws Exception {

    File sourceFile = new File(srcFullPath + File.separator + fileName);
    if (!sourceFile.exists()) {
      throw new Exception(fileName
          + " file doesn't exist at specified input directory: " + srcFullPath);
    }

  }

  /**
   * Compute.
   *
   * @throws Exception the exception
   */
  /* see superclass */
  @Override
  public void compute() throws Exception {
    logInfo("Starting " + getName());

    // No Molecular actions will be generated by this algorithm
    setMolecularActionFlag(false);
    
    // read in file termgroups.src
    BufferedReader in = new BufferedReader(new FileReader(new File(srcFullPath + File.separator + "termgroups.src")));
    String fileLine = "";
    Set<String> termgroups = new HashSet<>();
    
    // cache termgroups
    while ((fileLine = in.readLine()) != null) {
      String[] fields = FieldedStringTokenizer.split(fileLine, "|");
      termgroups.add(fields[0]);
    }    
    
    // read in file classes_atoms.src
    in = new BufferedReader(new FileReader(new File(srcFullPath + File.separator + "classes_atoms.src")));
    ValidationResult result = new ValidationResultJpa();
    Map<String, String> lowerToNativeMap = new HashMap<>();
    
    // do field and line checks
    // initialize caches
    while ((fileLine = in.readLine()) != null) {
      
      String[] fields = FieldedStringTokenizer.split(fileLine, "|");
      
      // check each row has the correct number of fields
      if (checkNames.contains("#ATOMS_1")) {
        if (fields.length != 14) {
          result
              .addError("ATOMS_1: incorrect number of fields in classes_atoms.src row: "
                  + fileLine);
        }
      }
      
      // check first field is an integer
      if (checkNames.contains("#ATOMS_2")) {
        try {
          Integer.parseInt(fields[0]);
        } catch (Exception e) {
          result
              .addError("ATOMS_2: First field in classes_atoms.src must be an integer. "
                  + fields[0]);
        }
      }
      
      // check last field is an integer
      if (checkNames.contains("#ATOMS_3")) {
        try {
          Integer.parseInt(fields[13]);
        } catch (Exception e) {
          result.addError("ATOMS_3: Last field in classes_atoms.src must be an integer. "
              + fields[0]);
        }
      }
      
      // check for angle brackets in string field
      if (checkNames.contains("#ATOMS_4")) {
        if (fields[8].contains("<") || fields[8].contains(">")) {
          result.addWarning(
              "ATOMS_4: String field in classes_atoms.src should not have angle brackets. "
                  + fields[8]);
        }
      }
      
      // check for valid termgroup
      if (checkNames.contains("#ATOMS_5")) {
        if (!termgroups.contains(fields[2]) && !fields[2].startsWith("SRC/")) {
          result.addError(
              "ATOMS_5: Termgroup in classes_atoms.src is invalid: " + fields[2]);
        }
      }

    }
    in.close();
    in = new BufferedReader(new FileReader(new File(srcFullPath + File.separator + "classes_atoms.src")));
    
    while ((fileLine = in.readLine()) != null) {
      
      
      String[] fields = FieldedStringTokenizer.split(fileLine, "|");

      // check for duplicate case-sensitive strings
      if (checkNames.contains("#ATOMS_6")) {
        if (lowerToNativeMap.values().contains(fields[7])) {
          result.addWarning("ATOMS_6: Duplicate case-sensitive strings: " + fields[7]);

          // check for duplicate case-insensitive strings
        } else if (lowerToNativeMap.keySet()
            .contains(fields[7].toLowerCase())) {
          result.addWarning(
              "ATOMS_6: Duplicate case-insensitive strings: " + fields[7].toLowerCase());

          // add it to the map
        } else {
          lowerToNativeMap.put(fields[7].toLowerCase(), fields[7]);
        }
      }
    }
    
    // print warnings and errors to log
    if (result.getWarnings().size() > 0) {
      for (String warning : result.getWarnings()) {
        logInfo(warning);
      }
    }
    if (result.getErrors().size() > 0) {
      for (String error : result.getErrors()) {
        logError(error);
      }
      throw new Exception(this.getName() + " Failed");
    }

    logInfo("Finished " + getName());
  }

  /**
   * Reset.
   *
   * @throws Exception the exception
   */
  /* see superclass */
  @Override
  public void reset() throws Exception {
    logInfo("Starting RESET " + getName());
    // n/a - No reset
    logInfo("Finished RESET " + getName());
  }

  /* see superclass */
  @Override
  public void checkProperties(Properties p) throws Exception {
    // n/a
  }

  /* see superclass */
  @Override
  public void setProperties(Properties p) throws Exception {
    if (p.getProperty("checkNames") != null) {
      checkNames =
          Arrays.asList(String.valueOf(p.getProperty("checkNames")).split(";"));
    }
  }

  /* see superclass */
  @Override
  public List<AlgorithmParameter> getParameters() throws Exception {
    final List<AlgorithmParameter> params = super.getParameters();

    // Integrity check names
    AlgorithmParameter param = new AlgorithmParameterJpa("Validation Checks", "checkNames",
        "The names of the validation checks to run", "e.g. #ATOMS_1", 200,
        AlgorithmParameter.Type.MULTI, "");

    List<String> validationChecks = new ArrayList<>();
    validationChecks.add("#ATOMS_1");
    validationChecks.add("#ATOMS_2");
    validationChecks.add("#ATOMS_3");
    validationChecks.add("#ATOMS_4");
    validationChecks.add("#ATOMS_5");
    validationChecks.add("#ATOMS_6");
    validationChecks.add("#ATOMS_7");
    validationChecks.add("#ATOMS_8");
    validationChecks.add("#ATOMS_9");
    validationChecks.add("#ATOMS_10");
    
    Collections.sort(validationChecks);
    param.setPossibleValues(validationChecks);
    params.add(param);
    
    return params;
  }

  @Override
  public String getDescription() {
    return "Validation checks related to atoms in the inversion files.";
  }
}