/*
 *    Copyright 2015 West Coast Informatics, LLC
 */
package com.wci.umls.server.services.handlers;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Date;
import java.util.Properties;

import javax.ws.rs.WebApplicationException;

import org.apache.commons.lang3.time.FastDateFormat;
import org.apache.log4j.Logger;

import com.wci.umls.server.helpers.ConfigUtility;
import com.wci.umls.server.helpers.LocalException;

/**
 * Handles exceptions.
 */
public class ExceptionHandler {

  /** Date format */
  public final static FastDateFormat df =
      FastDateFormat.getInstance("hh:mm:ss a");

  /**
   * Handle exception.
   *
   * @param e the e
   * @param whatIsHappening the what is happening
   * @throws Exception the web application exception
   */
  public static void handleException(Exception e, String whatIsHappening)
    throws Exception {
    handleException(e, whatIsHappening, "");
  }

  /**
   * Handle exception. For {@link LocalException} print the stack trace and
   * inform the user with a message generated by the application. For all other
   * exceptions, also send email to administrators with the message and the
   * stack trace.
   *
   * @param e the e
   * @param whatIsHappening the what is happening
   * @param userName the current user
   * @throws Exception the web application exception
   */
  public static void handleException(Exception e, String whatIsHappening,
    String userName) throws Exception {

    e.printStackTrace();
    if (e instanceof LocalException) {
      throw e;
    }
    if (e instanceof WebApplicationException) {
      throw (WebApplicationException) e;
    }

    try {
      final Properties config = ConfigUtility.getConfigProperties();
      final String subject = "Terminology Server Error Report";
      String from = null;
      if (config.containsKey("mail.smtp.from")) {
        from = config.getProperty("mail.smtp.from");
      } else {
        from = config.getProperty("mail.smtp.user");
      }
      final String recipients = config.getProperty("mail.smtp.to");

      // Bail if no recipients
      if (recipients == null || recipients.isEmpty()) {
        return;
      }

      final Properties props = new Properties();
      for (final Object prop : config.keySet()) {
        if (prop.toString().startsWith("mail.smtp")) {
          props.put(prop.toString(), config.getProperty(prop.toString()));
        }
      }
      final StringBuilder body = new StringBuilder();
      if (!(e instanceof LocalException))
        body.append("Unexpected error " + whatIsHappening
            + ". Please contact the administrator.").append("\n\n");

      try {
        body.append("HOST: " + InetAddress.getLocalHost().getHostName())
            .append("\n");
      } catch (UnknownHostException e1) {
        body.append("HOST:  unable to determine");
      }
      body.append("TIME: " + df.format(new Date())).append("\n");
      body.append("USER: " + userName).append("\n");

      body.append("MESSAGE: " + e.getMessage()).append("\n\n");
      final StringWriter out = new StringWriter();
      final PrintWriter pw = new PrintWriter(out);
      e.printStackTrace(pw);
      body.append(out.getBuffer());
      Logger.getLogger(ExceptionHandler.class)
          .info("Sending error email : " + props);
      if ("true".equals(config.getProperty("mail.enabled"))) {
        ConfigUtility.sendEmail(subject, from, recipients, body.toString(),
            props);
      } else {
        Logger.getLogger(ExceptionHandler.class)
            .info("Sending mail is disabled.");
      }
    } catch (Exception ex) {
      ex.printStackTrace();
      Logger.getLogger(ExceptionHandler.class)
          .error("Unable to handle exception");
    }

  }

}
